# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'XYR.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setLineWidth(1)
        self.title.setTextFormat(QtCore.Qt.AutoText)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setIndent(0)
        self.title.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.name = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name.setFont(font)
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setObjectName("name")
        self.horizontalLayout.addWidget(self.name)
        self.suspectButton = QtWidgets.QPushButton(self.centralwidget)
        self.suspectButton.setObjectName("suspectButton")
        self.horizontalLayout.addWidget(self.suspectButton)
        self.actionButon = QtWidgets.QPushButton(self.centralwidget)
        self.actionButon.setObjectName("actionButon")
        self.horizontalLayout.addWidget(self.actionButon)
        self.actionIn = QtWidgets.QPushButton(self.centralwidget)
        self.actionIn.setObjectName("actionIn")
        self.horizontalLayout2.addWidget(self.actionIn)
        self.positionButton = QtWidgets.QPushButton(self.centralwidget)
        self.positionButton.setObjectName("positionButton")
        self.horizontalLayout2.addWidget(self.positionButton)
        self.orbitButton = QtWidgets.QPushButton(self.centralwidget)
        self.orbitButton.setObjectName("orbitButton")
        self.horizontalLayout2.addWidget(self.orbitButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.table = QtWidgets.QTableWidget()
        self.table.setObjectName("table")
        self.verticalLayout.addWidget(self.table)
        self.suspectIn = QtWidgets.QPushButton(self.centralwidget)
        self.suspectIn.setObjectName("suspectIn")
        self.horizontalLayout2.addWidget(self.suspectIn)
        self.verticalLayout.addLayout(self.horizontalLayout2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("myICON.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)

        self.retranslateUi(MainWindow)
        self.actionIn.clicked.connect(self.action_in)
        self.suspectIn.clicked.connect(self.suspect_in)
        self.positionButton.clicked.connect(self.map_find)
        self.suspectButton.clicked.connect(self.suspect_select)
        self.actionButon.clicked.connect(self.find_action)
        self.orbitButton.clicked.connect(self.guiji_find)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "嫌疑人行为轨迹可视化系统"))
        self.title.setText(_translate("MainWindow", "嫌疑人行为轨迹可视化系统"))
        self.name.setText(_translate("MainWindow", "嫌疑人姓名："))
        self.actionButon.setText(_translate("MainWindow", "最近行为查询"))
        self.actionIn.setText(_translate("MainWindow", "最近行为录入"))
        self.positionButton.setText(_translate("MainWindow", "实时位置查询"))
        self.orbitButton.setText(_translate("MainWindow", "7天行动轨迹查询"))
        self.suspectIn.setText(_translate("MainWindow", "嫌疑人信息录入"))
        self.suspectButton.setText(_translate("MainWindow", "请输入嫌疑人姓名"))

